### ISSUE TITLE
Update events dependency

### ISSUE THREAD

**Issue by CarsonF** [goenning/typed-pg#1]
Most of [`EventEmitter`'s methods](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node.d.ts#L177-L182) now return `this` instead of `EventEmitter`.

I'm not sure what _typings_ is doing, but it's pulling in a newer version and tsc is throwing errors. Maybe because the dependency is ambient..

Would you mind updating?

**Comment by goenning** [comment]
Good catch, thank you. 

This is resolved with commit 83236e7c54254e5e4135efc79280c91d3ba2d819.
I'll update the registry as soon as possible.
