### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by felixfbecker** [goenning/typed-pg#10]
``` js
var types = require('pg').types
types.setTypeParser(20, function(val) {
  return parseInt(val)
})
```

Documentation here: https://www.npmjs.com/package/pg-types

**Comment by 0815fox** [comment]
@goenning:
Should we follow the structure and add it as separate module as well?

**Comment by felixfbecker** [comment]
@0815fox You can import it as a seperate module, but the docs actually say you should access it through `pg.types`. As the definition is only a couple of lines, I would say keep it in here for now.
