### ISSUE TITLE
No longer builds due to TlsOptions missing.

### ISSUE THREAD

**Issue by ihsw** [goenning/typed-pg#15]
TlsOptions was removed earlier this month.

https://github.com/types/env-node/commit/fd484a52831262f3f4a5958cd732bbd590c3d4c7#diff-454ff0a7aff1da6588b816d269cf7ff9L1605

Currently I'm copying the removed portion into a `pg` typings file that I'll keep on hand.

Not sure what the recommended fix is for you guys though.

I have opened an issue on their issue tracker to see what's up.

https://github.com/types/env-node/issues/45

**Comment by blakeembrey** [comment]
Happy to accept a PR. It looks like it should use `ConnectOptions` instead (and perhaps only a subset, but it's fine until we can be index types with TypeScript). In source code: https://github.com/brianc/node-postgres/blob/83a946f61cb9e74c7f499e44d03a268c399bd623/lib/connection.js#L91-L101
