### ISSUE TITLE
Wrong definition of DoneCallback

### ISSUE THREAD

**Issue by andhieka** [goenning/typed-pg#18]
The README specifically mentions we should pass `err` to `done` callback. However, this repository declares `DoneCallback` as parameterless function. This causes error when compiling my TypeScript project.

This is how `done` should be called:
<img width="592" alt="untitled" src="https://cloud.githubusercontent.com/assets/6689743/23821484/d2f37d86-066e-11e7-820b-fe7aed6e3ea8.png">

This is the definition of `DoneCallback` (line 130):
<img width="424" alt="untitled 2" src="https://cloud.githubusercontent.com/assets/6689743/23821520/87ad991e-066f-11e7-816e-15e8a824c017.png">

Check this specific line: https://github.com/types/npm-pg/blob/c8826dc3f6afdbe02d7e9622a664d1be9095cf8e/index.d.ts#L9

**Comment by andhieka** [comment]
On a separate note, another error (visible at line 123 above) is:
```
index.d.ts(123,10): error TS2305: Module '"tls"' has no exported member 'Co
nnectOptions
```

**Comment by blakeembrey** [comment]
Which node definition are you using? It's based on https://github.com/types/env-node. I just updated the `DoneCallback` using https://github.com/types/npm-pg/commit/ba5ea76de73f2cd352e3b69f149cd97dfba1d4c9.
