### ISSUE TITLE
Should we think about project naming?

### ISSUE THREAD

**Issue by 0815fox** [goenning/typed-pg#8]
This project is names typed-pg, the other one npm-pg-pool. Would it break anything if this one was renamed to npm-pg?

**Comment by goenning** [comment]
`typed-` was the previous preffix for typing projects but now it's `npm-`.
If we change the repository name, we'll need to update this as well [typings/registry](https://github.com/typings/registry/blob/master/npm/pg.json).

I think we can leave like this for now and focus on fixing #9. When we're done, we can send a single PR to the registry with both upgrading to v6 and rename.

**Comment by blakeembrey** [comment]
I think this has been resolved. Let me know if that's incorrect.
