### ISSUE TITLE
Update typings for node-postgres version 6

### ISSUE THREAD

**Issue by 0815fox** [goenning/typed-pg#9]
I suggest we skip version 5 as it did not live very long. So this is a ticket handling the support for version 6, until I submit a PR.

Roadmap: due to business I will try to do it until next monday or tuesday (12th of july).

**Comment by goenning** [comment]
Hello @0815fox. I've update typed-pg and npm-pg-pool to match pg v6 and add each other as a dependency. By doing that we now don't have more duplicates interface like Client, Query, etc. I would like you to take a look at it before merging into master. All changes were committed to `vnext` tag.

https://github.com/typed-typings/typed-pg/tree/vnext
https://github.com/typed-typings/npm-pg-pool/tree/vnext

**Comment by 0815fox** [comment]
Hi Guilherme,
oh it looks great, thank you! I did not even expect it to work seamlessly with circular dependencies, interesting though, that it still works. I will take a look at it today and provide feedback. This week I do not have too much time, but, in case there is anything else I can/shall do, let me know!
Michael

**Comment by 0815fox** [comment]
@goenning: Shouldn't we switch the typed-pg-module to use the declare syntax as well?

Also, shouldn't:

```
export class Pool extends PgPool
{

}
```

better be sth. like:

```
export {PgPool as Pool} from "pg-pool"
```

not sure however, if/how that works in combination with the declare syntax...

**Comment by goenning** [comment]
@0815fox after an extensive battle with circular dependencies, I think I managed to get it working. I'll close this issue for now

Feel free to send any PR to improve it 👍
